"""
Liste statiche per select/dropdown nei form.
"""

PAESI = [
    ('', '— Seleziona paese —'),
    ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'),
    ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua e Barbuda', 'Antigua e Barbuda'),
    ('Arabia Saudita', 'Arabia Saudita'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'),
    ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaigian', 'Azerbaigian'),
    ('Bahamas', 'Bahamas'), ('Bahrein', 'Bahrein'), ('Bangladesh', 'Bangladesh'),
    ('Barbados', 'Barbados'), ('Belgio', 'Belgio'), ('Belize', 'Belize'),
    ('Benin', 'Benin'), ('Bhutan', 'Bhutan'), ('Bielorussia', 'Bielorussia'),
    ('Bolivia', 'Bolivia'), ('Bosnia ed Erzegovina', 'Bosnia ed Erzegovina'),
    ('Botswana', 'Botswana'), ('Brasile', 'Brasile'), ('Brunei', 'Brunei'),
    ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'),
    ('Cambogia', 'Cambogia'), ('Camerun', 'Camerun'), ('Canada', 'Canada'),
    ('Capo Verde', 'Capo Verde'), ('Ciad', 'Ciad'), ('Cile', 'Cile'),
    ('Cina', 'Cina'), ('Cipro', 'Cipro'), ('Colombia', 'Colombia'),
    ('Comore', 'Comore'), ('Congo', 'Congo'), ('Corea del Nord', 'Corea del Nord'),
    ('Corea del Sud', 'Corea del Sud'), ('Costa Rica', 'Costa Rica'),
    ('Costa d\'Avorio', 'Costa d\'Avorio'), ('Croazia', 'Croazia'), ('Cuba', 'Cuba'),
    ('Danimarca', 'Danimarca'), ('Dominica', 'Dominica'),
    ('Repubblica Dominicana', 'Repubblica Dominicana'),
    ('Ecuador', 'Ecuador'), ('Egitto', 'Egitto'), ('El Salvador', 'El Salvador'),
    ('Emirati Arabi Uniti', 'Emirati Arabi Uniti'), ('Eritrea', 'Eritrea'),
    ('Estonia', 'Estonia'), ('Etiopia', 'Etiopia'),
    ('Figi', 'Figi'), ('Filippine', 'Filippine'), ('Finlandia', 'Finlandia'),
    ('Francia', 'Francia'),
    ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'),
    ('Germania', 'Germania'), ('Ghana', 'Ghana'), ('Giamaica', 'Giamaica'),
    ('Giappone', 'Giappone'), ('Gibuti', 'Gibuti'), ('Giordania', 'Giordania'),
    ('Grecia', 'Grecia'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'),
    ('Guinea-Bissau', 'Guinea-Bissau'), ('Guinea Equatoriale', 'Guinea Equatoriale'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'), ('Honduras', 'Honduras'),
    ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'),
    ('Iraq', 'Iraq'), ('Irlanda', 'Irlanda'), ('Islanda', 'Islanda'),
    ('Israele', 'Israele'), ('Italia', 'Italia'),
    ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kirghizistan', 'Kirghizistan'),
    ('Kiribati', 'Kiribati'), ('Kuwait', 'Kuwait'),
    ('Laos', 'Laos'), ('Lesotho', 'Lesotho'), ('Lettonia', 'Lettonia'),
    ('Libano', 'Libano'), ('Liberia', 'Liberia'), ('Libia', 'Libia'),
    ('Liechtenstein', 'Liechtenstein'), ('Lituania', 'Lituania'),
    ('Lussemburgo', 'Lussemburgo'),
    ('Macedonia del Nord', 'Macedonia del Nord'), ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'), ('Maldive', 'Maldive'), ('Malesia', 'Malesia'),
    ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marocco', 'Marocco'),
    ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Messico', 'Messico'),
    ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'),
    ('Montenegro', 'Montenegro'), ('Mozambico', 'Mozambico'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namibia'), ('Nepal', 'Nepal'), ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Norvegia', 'Norvegia'),
    ('Nuova Zelanda', 'Nuova Zelanda'),
    ('Oman', 'Oman'),
    ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'),
    ('Papua Nuova Guinea', 'Papua Nuova Guinea'), ('Paraguay', 'Paraguay'),
    ('Perù', 'Perù'), ('Polonia', 'Polonia'), ('Portogallo', 'Portogallo'),
    ('Qatar', 'Qatar'),
    ('Regno Unito', 'Regno Unito'), ('Repubblica Ceca', 'Repubblica Ceca'),
    ('Romania', 'Romania'), ('Ruanda', 'Ruanda'), ('Russia', 'Russia'),
    ('Saint Kitts e Nevis', 'Saint Kitts e Nevis'), ('Saint Lucia', 'Saint Lucia'),
    ('Salvador', 'Salvador'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'),
    ('São Tomé e Príncipe', 'São Tomé e Príncipe'), ('Senegal', 'Senegal'),
    ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'),
    ('Singapore', 'Singapore'), ('Siria', 'Siria'), ('Slovenia', 'Slovenia'),
    ('Slovacchia', 'Slovacchia'), ('Somalia', 'Somalia'), ('Spagna', 'Spagna'),
    ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Sudan del Sud', 'Sudan del Sud'),
    ('Suriname', 'Suriname'), ('Svezia', 'Svezia'), ('Svizzera', 'Svizzera'),
    ('Swaziland', 'Swaziland'),
    ('Tagikistan', 'Tagikistan'), ('Tanzania', 'Tanzania'), ('Thailandia', 'Thailandia'),
    ('Timor Est', 'Timor Est'), ('Togo', 'Togo'), ('Tonga', 'Tonga'),
    ('Trinidad e Tobago', 'Trinidad e Tobago'), ('Tunisia', 'Tunisia'),
    ('Turchia', 'Turchia'), ('Turkmenistan', 'Turkmenistan'),
    ('Tuvalu', 'Tuvalu'),
    ('Uganda', 'Uganda'), ('Ucraina', 'Ucraina'), ('Ungheria', 'Ungheria'),
    ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'),
    ('Vanuatu', 'Vanuatu'), ('Vaticano', 'Vaticano'), ('Venezuela', 'Venezuela'),
    ('Vietnam', 'Vietnam'),
    ('Yemen', 'Yemen'),
    ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe'),
    ('Stati Uniti', 'Stati Uniti'),
]

NAZIONALITA = [
    ('', '— Seleziona nazionalità —'),
    ('Afghana', 'Afghana'), ('Albanese', 'Albanese'), ('Algerina', 'Algerina'),
    ('Andorrana', 'Andorrana'), ('Angolana', 'Angolana'), ('Saudita', 'Saudita'),
    ('Argentina', 'Argentina'), ('Armena', 'Armena'), ('Australiana', 'Australiana'),
    ('Austriaca', 'Austriaca'), ('Azerbaigiana', 'Azerbaigiana'),
    ('Bangladese', 'Bangladese'), ('Belga', 'Belga'), ('Boliviana', 'Boliviana'),
    ('Bosniaca', 'Bosniaca'), ('Brasiliana', 'Brasiliana'), ('Britannica', 'Britannica'),
    ('Bulgara', 'Bulgara'),
    ('Cambogiana', 'Cambogiana'), ('Camerunense', 'Camerunense'),
    ('Canadese', 'Canadese'), ('Cilena', 'Cilena'), ('Cinese', 'Cinese'),
    ('Cipriota', 'Cipriota'), ('Colombiana', 'Colombiana'), ('Croata', 'Croata'),
    ('Cubana', 'Cubana'),
    ('Danese', 'Danese'),
    ('Ecuadoriana', 'Ecuadoriana'), ('Egiziana', 'Egiziana'),
    ('Emiratina', 'Emiratina'), ('Eritrea', 'Eritrea'), ('Estone', 'Estone'),
    ('Etiope', 'Etiope'),
    ('Filippina', 'Filippina'), ('Finlandese', 'Finlandese'), ('Francese', 'Francese'),
    ('Georgiana', 'Georgiana'), ('Tedesca', 'Tedesca'), ('Ghanese', 'Ghanese'),
    ('Giamaicana', 'Giamaicana'), ('Giapponese', 'Giapponese'),
    ('Giordana', 'Giordana'), ('Greca', 'Greca'), ('Guatemalteca', 'Guatemalteca'),
    ('Honduregna', 'Honduregna'),
    ('Indiana', 'Indiana'), ('Indonesiana', 'Indonesiana'),
    ('Iraniana', 'Iraniana'), ('Irachena', 'Irachena'), ('Irlandese', 'Irlandese'),
    ('Islandese', 'Islandese'), ('Israeliana', 'Israeliana'), ('Italiana', 'Italiana'),
    ('Kazaka', 'Kazaka'), ('Keniota', 'Keniota'), ('Kuwaitiana', 'Kuwaitiana'),
    ('Laotiana', 'Laotiana'), ('Lettone', 'Lettone'), ('Libanese', 'Libanese'),
    ('Libica', 'Libica'), ('Lituana', 'Lituana'), ('Lussemburghese', 'Lussemburghese'),
    ('Macedone', 'Macedone'), ('Malgascia', 'Malgascia'), ('Malese', 'Malese'),
    ('Marocchina', 'Marocchina'), ('Maltese', 'Maltese'),
    ('Mauritana', 'Mauritana'), ('Messicana', 'Messicana'), ('Moldava', 'Moldava'),
    ('Monegasca', 'Monegasca'), ('Mongola', 'Mongola'), ('Montenegrina', 'Montenegrina'),
    ('Mozambicana', 'Mozambicana'),
    ('Nepalese', 'Nepalese'), ('Neozelandese', 'Neozelandese'),
    ('Nicaraguense', 'Nicaraguense'), ('Nigeriana', 'Nigeriana'), ('Norvegese', 'Norvegese'),
    ('Omanita', 'Omanita'),
    ('Pakistana', 'Pakistana'), ('Panamense', 'Panamense'), ('Paraguaiana', 'Paraguaiana'),
    ('Peruviana', 'Peruviana'), ('Polacca', 'Polacca'), ('Portoghese', 'Portoghese'),
    ('Qatariota', 'Qatariota'),
    ('Rumena', 'Rumena'), ('Ruandese', 'Ruandese'), ('Russa', 'Russa'),
    ('Salvadoregna', 'Salvadoregna'), ('Senegalese', 'Senegalese'),
    ('Serba', 'Serba'), ('Singaporiana', 'Singaporiana'),
    ('Siriana', 'Siriana'), ('Slovacca', 'Slovacca'), ('Slovena', 'Slovena'),
    ('Somala', 'Somala'), ('Spagnola', 'Spagnola'), ('Srilankese', 'Srilankese'),
    ('Statunitense', 'Statunitense'),
    ('Sudanese', 'Sudanese'), ('Sudafricana', 'Sudafricana'),
    ('Svedese', 'Svedese'), ('Svizzera', 'Svizzera'),
    ('Tailandese', 'Tailandese'), ('Tanzaniana', 'Tanzaniana'),
    ('Tunisina', 'Tunisina'), ('Turca', 'Turca'),
    ('Ucraina', 'Ucraina'), ('Ungherese', 'Ungherese'),
    ('Uruguaiana', 'Uruguaiana'), ('Uzbeka', 'Uzbeka'),
    ('Venezuelana', 'Venezuelana'), ('Vietnamita', 'Vietnamita'),
    ('Yemenita', 'Yemenita'),
    ('Zambiana', 'Zambiana'), ('Zimbabwese', 'Zimbabwese'),
]

LINGUE = [
    ('', '— Seleziona lingua —'),
    ('Afrikaans', 'Afrikaans'),
    ('Albanese', 'Albanese'),
    ('Amarico', 'Amarico'),
    ('Arabo', 'Arabo'),
    ('Armeno', 'Armeno'),
    ('Azerbaigiano', 'Azerbaigiano'),
    ('Bengalese', 'Bengalese'),
    ('Bielorusso', 'Bielorusso'),
    ('Birmano', 'Birmano'),
    ('Bosniaco', 'Bosniaco'),
    ('Bulgaro', 'Bulgaro'),
    ('Cambogiano (Khmer)', 'Cambogiano (Khmer)'),
    ('Catalano', 'Catalano'),
    ('Ceco', 'Ceco'),
    ('Cinese (Cantonese)', 'Cinese (Cantonese)'),
    ('Cinese (Mandarino)', 'Cinese (Mandarino)'),
    ('Coreano', 'Coreano'),
    ('Croato', 'Croato'),
    ('Curdo', 'Curdo'),
    ('Danese', 'Danese'),
    ('Dari', 'Dari'),
    ('Ebraico', 'Ebraico'),
    ('Estone', 'Estone'),
    ('Filippino (Tagalog)', 'Filippino (Tagalog)'),
    ('Finlandese', 'Finlandese'),
    ('Francese', 'Francese'),
    ('Gallese', 'Gallese'),
    ('Georgiano', 'Georgiano'),
    ('Giapponese', 'Giapponese'),
    ('Greco', 'Greco'),
    ('Gujarati', 'Gujarati'),
    ('Hindi', 'Hindi'),
    ('Indonesiano', 'Indonesiano'),
    ('Inglese', 'Inglese'),
    ('Islandese', 'Islandese'),
    ('Italiano', 'Italiano'),
    ('Kazako', 'Kazako'),
    ('Kirghiso', 'Kirghiso'),
    ('Laotiano', 'Laotiano'),
    ('Lettone', 'Lettone'),
    ('Lituano', 'Lituano'),
    ('Macedone', 'Macedone'),
    ('Malaio', 'Malaio'),
    ('Maltese', 'Maltese'),
    ('Marathi', 'Marathi'),
    ('Mongolo', 'Mongolo'),
    ('Nepalese', 'Nepalese'),
    ('Norvegese', 'Norvegese'),
    ('Olandese', 'Olandese'),
    ('Pashto', 'Pashto'),
    ('Persiano (Farsi)', 'Persiano (Farsi)'),
    ('Polacco', 'Polacco'),
    ('Portoghese', 'Portoghese'),
    ('Punjabi', 'Punjabi'),
    ('Romeno', 'Romeno'),
    ('Russo', 'Russo'),
    ('Serbo', 'Serbo'),
    ('Singalese', 'Singalese'),
    ('Slovacco', 'Slovacco'),
    ('Sloveno', 'Sloveno'),
    ('Somalo', 'Somalo'),
    ('Spagnolo', 'Spagnolo'),
    ('Swahili', 'Swahili'),
    ('Svedese', 'Svedese'),
    ('Tagico', 'Tagico'),
    ('Tailandese', 'Tailandese'),
    ('Tamil', 'Tamil'),
    ('Tedesco', 'Tedesco'),
    ('Telugu', 'Telugu'),
    ('Turco', 'Turco'),
    ('Turkmeno', 'Turkmeno'),
    ('Ucraino', 'Ucraino'),
    ('Ungherese', 'Ungherese'),
    ('Urdu', 'Urdu'),
    ('Uzbeko', 'Uzbeko'),
    ('Vietnamita', 'Vietnamita'),
    ('Yoruba', 'Yoruba'),
    ('Zulu', 'Zulu'),
]

TOUR_CATEGORIE = [
    ('', '— Seleziona —'),
    ('Culturale', 'Culturale'),
    ('Avventura', 'Avventura'),
    ('Gastronomia', 'Gastronomia'),
    ('Benessere', 'Benessere'),
    ('Mare', 'Mare'),
    ('Montagna', 'Montagna'),
    ('Città', 'Città'),
    ('Safari', 'Safari'),
    ('Crociera', 'Crociera'),
    ('Fede', 'Fede'),
    ('Religione', 'Religione'),
]

ESPERIENZA_CATEGORIE = [
    ('', '— Seleziona —'),
    ('Arte & Cultura', 'Arte & Cultura'),
    ('Food & Wine', 'Food & Wine'),
    ('Natura', 'Natura'),
    ('Sport', 'Sport'),
    ('Benessere', 'Benessere'),
    ('Shopping', 'Shopping'),
    ('Nightlife', 'Nightlife'),
    ('Family', 'Family'),
    ('Fede', 'Fede'),
    ('Religione', 'Religione'),
]
