"""Add is_demo to Tour, Viaggio, Pacchetto

Revision ID: 10fc9a6d6028
Revises: 123456789abc
Create Date: 2026-03-12 11:50:37.925052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fc9a6d6028'
down_revision = '123456789abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    with op.batch_alter_table('esperienze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    with op.batch_alter_table('pacchetti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    with op.batch_alter_table('viaggi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaggi', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('pacchetti', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('esperienze', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###
