"""Add is_demo field to clienti

Revision ID: 123456789abc
Revises: 74c5102720ab
Create Date: 2026-03-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123456789abc'
down_revision = '74c5102720ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clienti', sa.Column('is_demo', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clienti', 'is_demo')
    # ### end Alembic commands ###