"""Add billing fields to Viaggio

Revision ID: 74c5102720ab
Revises: 
Create Date: 2026-03-11 17:21:21.395225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c5102720ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaggi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ricevuta_emessa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_ricevuta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fattura_emessa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_fattura', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('numero_ricevuta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_fattura', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaggi', schema=None) as batch_op:
        batch_op.drop_column('numero_fattura')
        batch_op.drop_column('numero_ricevuta')
        batch_op.drop_column('data_fattura')
        batch_op.drop_column('fattura_emessa')
        batch_op.drop_column('data_ricevuta')
        batch_op.drop_column('ricevuta_emessa')

    # ### end Alembic commands ###
